silk-touch-spawners: false
aesthetic-command-blocks: false
rain-water-buckets: false
self-powered-lamps: false
bone-meal-ferns: false
infinite-lava-sources: false
hopper-cauldron-braziers: false
recipes:
  perma-dirt: false
  podzol: false
  mycelium: false
  end-portal-frame: false
  cracked-stone-brick: false
  name-tag: false
  saddle: false
  horse-armor: false
  double-stone-slab: false
  full-stone-slab: false
  dead-bush: false
  cobweb: false
  bleach-wool: false
  bleach-clay: false
  bleach-glass: false