silk-touch-spawners: false
aesthetic-command-blocks: false
rain-water-buckets: false
self-powered-lamps: false
recipes:
  perma-dirt: false
  podzol: false
  mycelium: false
  end-portal-frame: false
  cracked-stone-brick: false
  name-tag: false
  saddle: false
  horse-armor: false
  double-stone-slab: false
  dead-bush: false
  cobweb: false